// <auto-generated />
using System;
using Lewiss.Pricing.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lewiss.Pricing.Data.Migrations
{
    [DbContext(typeof(PricingDbContext))]
    [Migration("20260128124412_TypeInOperationSideOptionVariation")]
    partial class TypeInOperationSideOptionVariation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("ExternalMapping")
                        .HasColumnType("char(36)");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Mobile")
                        .IsUnique();

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<Guid>("ExternalMapping")
                        .HasColumnType("char(36)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<decimal>("InstallHeight")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("RemoteChannel")
                        .HasColumnType("int");

                    b.Property<int>("RemoteNumber")
                        .HasColumnType("int");

                    b.Property<int>("Reveal")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.Property<int>("WorksheetId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("WorksheetId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.ProductOption", b =>
                {
                    b.Property<int>("ProductOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductOptionId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProductOptionId");

                    b.ToTable("ProductOption");

                    b.HasData(
                        new
                        {
                            ProductOptionId = 1,
                            Name = "FitType"
                        },
                        new
                        {
                            ProductOptionId = 2,
                            Name = "FixingTo"
                        },
                        new
                        {
                            ProductOptionId = 3,
                            Name = "ProductType"
                        },
                        new
                        {
                            ProductOptionId = 4,
                            Name = "Fabric"
                        },
                        new
                        {
                            ProductOptionId = 5,
                            Name = "OperationType"
                        },
                        new
                        {
                            ProductOptionId = 6,
                            Name = "OperationSide"
                        },
                        new
                        {
                            ProductOptionId = 7,
                            Name = "HeadrailColour"
                        },
                        new
                        {
                            ProductOptionId = 8,
                            Name = "SideChannelColour"
                        },
                        new
                        {
                            ProductOptionId = 9,
                            Name = "RollType"
                        },
                        new
                        {
                            ProductOptionId = 10,
                            Name = "ChainColour"
                        },
                        new
                        {
                            ProductOptionId = 11,
                            Name = "ChainLength"
                        },
                        new
                        {
                            ProductOptionId = 12,
                            Name = "BracketType"
                        },
                        new
                        {
                            ProductOptionId = 13,
                            Name = "BracketColour"
                        },
                        new
                        {
                            ProductOptionId = 14,
                            Name = "BottomRailType"
                        },
                        new
                        {
                            ProductOptionId = 15,
                            Name = "BottomRailColour"
                        },
                        new
                        {
                            ProductOptionId = 16,
                            Name = "PelmetType"
                        },
                        new
                        {
                            ProductOptionId = 17,
                            Name = "PelmetColour"
                        });
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.ProductOptionVariation", b =>
                {
                    b.Property<int>("ProductOptionVariationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductOptionVariationId"));

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProductOptionId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProductOptionVariationId");

                    b.HasIndex("ProductOptionId");

                    b.ToTable("ProductOptionVariation");

                    b.HasData(
                        new
                        {
                            ProductOptionVariationId = 1,
                            Price = 0.0m,
                            ProductOptionId = 1,
                            Value = "Inside"
                        },
                        new
                        {
                            ProductOptionVariationId = 2,
                            Price = 0.0m,
                            ProductOptionId = 1,
                            Value = "Outside"
                        },
                        new
                        {
                            ProductOptionVariationId = 3,
                            Price = 0.0m,
                            ProductOptionId = 2,
                            Value = "Wood"
                        },
                        new
                        {
                            ProductOptionVariationId = 4,
                            Price = 0.0m,
                            ProductOptionId = 3,
                            Value = "Kinetics Cellular"
                        },
                        new
                        {
                            ProductOptionVariationId = 5,
                            Price = 0.0m,
                            ProductOptionId = 3,
                            Value = "Kinetics Roller"
                        },
                        new
                        {
                            ProductOptionVariationId = 6,
                            Price = 0.0m,
                            ProductOptionId = 4,
                            Value = "Translucent White"
                        },
                        new
                        {
                            ProductOptionVariationId = 7,
                            Price = 0.0m,
                            ProductOptionId = 4,
                            Value = "Everyday Vinyl Collection - Polar"
                        },
                        new
                        {
                            ProductOptionVariationId = 8,
                            Price = 250.0m,
                            ProductOptionId = 5,
                            Value = "Lithium-ion"
                        },
                        new
                        {
                            ProductOptionVariationId = 9,
                            Price = 0.0m,
                            ProductOptionId = 5,
                            Value = "Cord"
                        },
                        new
                        {
                            ProductOptionVariationId = 10,
                            Price = 0.0m,
                            ProductOptionId = 5,
                            Value = "Chain"
                        },
                        new
                        {
                            ProductOptionVariationId = 11,
                            Price = 0.00m,
                            ProductOptionId = 6,
                            Value = "Left"
                        },
                        new
                        {
                            ProductOptionVariationId = 12,
                            Price = 0.00m,
                            ProductOptionId = 6,
                            Value = "Right"
                        },
                        new
                        {
                            ProductOptionVariationId = 13,
                            Price = 0.00m,
                            ProductOptionId = 7,
                            Value = "White"
                        },
                        new
                        {
                            ProductOptionVariationId = 14,
                            Price = 0.00m,
                            ProductOptionId = 7,
                            Value = "Black"
                        },
                        new
                        {
                            ProductOptionVariationId = 15,
                            Price = 0.00m,
                            ProductOptionId = 8,
                            Value = "White"
                        },
                        new
                        {
                            ProductOptionVariationId = 16,
                            Price = 0.00m,
                            ProductOptionId = 8,
                            Value = "Black"
                        },
                        new
                        {
                            ProductOptionVariationId = 17,
                            Price = 0.00m,
                            ProductOptionId = 9,
                            Value = "Front"
                        },
                        new
                        {
                            ProductOptionVariationId = 18,
                            Price = 0.00m,
                            ProductOptionId = 9,
                            Value = "Back"
                        },
                        new
                        {
                            ProductOptionVariationId = 19,
                            Price = 0.00m,
                            ProductOptionId = 10,
                            Value = "White"
                        },
                        new
                        {
                            ProductOptionVariationId = 20,
                            Price = 0.00m,
                            ProductOptionId = 10,
                            Value = "Black"
                        },
                        new
                        {
                            ProductOptionVariationId = 21,
                            Price = 0.00m,
                            ProductOptionId = 10,
                            Value = "Grey"
                        },
                        new
                        {
                            ProductOptionVariationId = 22,
                            Price = 32.00m,
                            ProductOptionId = 10,
                            Value = "Stainless"
                        },
                        new
                        {
                            ProductOptionVariationId = 23,
                            Price = 0.00m,
                            ProductOptionId = 11,
                            Value = "750"
                        },
                        new
                        {
                            ProductOptionVariationId = 24,
                            Price = 0.00m,
                            ProductOptionId = 11,
                            Value = "1000"
                        },
                        new
                        {
                            ProductOptionVariationId = 25,
                            Price = 0.00m,
                            ProductOptionId = 11,
                            Value = "1250"
                        },
                        new
                        {
                            ProductOptionVariationId = 26,
                            Price = 0.00m,
                            ProductOptionId = 11,
                            Value = "1500"
                        },
                        new
                        {
                            ProductOptionVariationId = 27,
                            Price = 0.00m,
                            ProductOptionId = 11,
                            Value = "1750"
                        },
                        new
                        {
                            ProductOptionVariationId = 28,
                            Price = 0.00m,
                            ProductOptionId = 11,
                            Value = "2000"
                        },
                        new
                        {
                            ProductOptionVariationId = 29,
                            Price = 0.00m,
                            ProductOptionId = 11,
                            Value = "2250"
                        },
                        new
                        {
                            ProductOptionVariationId = 30,
                            Price = 0.00m,
                            ProductOptionId = 11,
                            Value = "2500"
                        },
                        new
                        {
                            ProductOptionVariationId = 31,
                            Price = 0.00m,
                            ProductOptionId = 11,
                            Value = "2750"
                        },
                        new
                        {
                            ProductOptionVariationId = 32,
                            Price = 0.00m,
                            ProductOptionId = 12,
                            Value = "Standard"
                        },
                        new
                        {
                            ProductOptionVariationId = 33,
                            Price = 0.00m,
                            ProductOptionId = 12,
                            Value = "Extra Large"
                        },
                        new
                        {
                            ProductOptionVariationId = 34,
                            Price = 0.00m,
                            ProductOptionId = 13,
                            Value = "White"
                        },
                        new
                        {
                            ProductOptionVariationId = 35,
                            Price = 0.00m,
                            ProductOptionId = 13,
                            Value = "Black"
                        },
                        new
                        {
                            ProductOptionVariationId = 36,
                            Price = 0.00m,
                            ProductOptionId = 14,
                            Value = "Flat"
                        },
                        new
                        {
                            ProductOptionVariationId = 37,
                            Price = 25.00m,
                            ProductOptionId = 14,
                            Value = "Deluxe"
                        },
                        new
                        {
                            ProductOptionVariationId = 38,
                            Price = 0.00m,
                            ProductOptionId = 15,
                            Value = "White"
                        },
                        new
                        {
                            ProductOptionVariationId = 39,
                            Price = 0.00m,
                            ProductOptionId = 15,
                            Value = "Black"
                        },
                        new
                        {
                            ProductOptionVariationId = 40,
                            Price = 0.00m,
                            ProductOptionId = 15,
                            Value = "Silver"
                        },
                        new
                        {
                            ProductOptionVariationId = 41,
                            Price = 0.00m,
                            ProductOptionId = 15,
                            Value = "Off White"
                        },
                        new
                        {
                            ProductOptionVariationId = 42,
                            Price = 0.00m,
                            ProductOptionId = 16,
                            Value = "None"
                        },
                        new
                        {
                            ProductOptionVariationId = 43,
                            Price = 0.00m,
                            ProductOptionId = 17,
                            Value = "White"
                        },
                        new
                        {
                            ProductOptionVariationId = 44,
                            Price = 0.00m,
                            ProductOptionId = 17,
                            Value = "Black"
                        });
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.Worksheet", b =>
                {
                    b.Property<int>("WorksheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WorksheetId"));

                    b.Property<decimal>("CallOutFee")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("ExternalMapping")
                        .HasColumnType("char(36)");

                    b.Property<bool>("NewBuild")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("WorksheetId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Worksheet");
                });

            modelBuilder.Entity("ProductProductOptionVariation", b =>
                {
                    b.Property<int>("OptionVariationsProductOptionVariationId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsProductId")
                        .HasColumnType("int");

                    b.HasKey("OptionVariationsProductOptionVariationId", "ProductsProductId");

                    b.HasIndex("ProductsProductId");

                    b.ToTable("ProductProductOptionVariation");
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.Product", b =>
                {
                    b.HasOne("Lewiss.Pricing.Data.Model.Worksheet", "Worksheet")
                        .WithMany()
                        .HasForeignKey("WorksheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worksheet");
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.ProductOptionVariation", b =>
                {
                    b.HasOne("Lewiss.Pricing.Data.Model.ProductOption", "ProductOption")
                        .WithMany("ProductOptionVariation")
                        .HasForeignKey("ProductOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductOption");
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.Worksheet", b =>
                {
                    b.HasOne("Lewiss.Pricing.Data.Model.Customer", "Customer")
                        .WithMany("CurrentWorksheets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ProductProductOptionVariation", b =>
                {
                    b.HasOne("Lewiss.Pricing.Data.Model.ProductOptionVariation", null)
                        .WithMany()
                        .HasForeignKey("OptionVariationsProductOptionVariationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lewiss.Pricing.Data.Model.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.Customer", b =>
                {
                    b.Navigation("CurrentWorksheets");
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.ProductOption", b =>
                {
                    b.Navigation("ProductOptionVariation");
                });
#pragma warning restore 612, 618
        }
    }
}
