// <auto-generated />
using System;
using Lewiss.Pricing.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lewiss.Pricing.Data.Migrations
{
    [DbContext(typeof(PricingDbContext))]
    [Migration("20260206045144_InitialCreateForSQLServer")]
    partial class InitialCreateForSQLServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ExternalMapping")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Mobile")
                        .IsUnique();

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.Fabric.Price.FabricPrice", b =>
                {
                    b.Property<int>("FabricPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FabricPriceId"));

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Opacity")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("FabricPriceId");

                    b.HasAlternateKey("Width", "Height", "Opacity", "ProductType");

                    b.ToTable("FabricPrice");
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.Fabric.Type.KineticsCellularFabric", b =>
                {
                    b.Property<int>("KineticsCellularFabricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KineticsCellularFabricId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Multiplier")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Opacity")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProductOptionVariationId")
                        .HasColumnType("int");

                    b.HasKey("KineticsCellularFabricId");

                    b.HasAlternateKey("Code", "Colour", "Opacity");

                    b.HasIndex("ProductOptionVariationId")
                        .IsUnique();

                    b.ToTable("KineticsCellularFabric");

                    b.HasData(
                        new
                        {
                            KineticsCellularFabricId = 1,
                            Code = "001",
                            Colour = "Cotton",
                            Multiplier = 1.0m,
                            Opacity = "Translucent",
                            ProductOptionVariationId = 53
                        },
                        new
                        {
                            KineticsCellularFabricId = 2,
                            Code = "005",
                            Colour = "Cream",
                            Multiplier = 1.0m,
                            Opacity = "Translucent",
                            ProductOptionVariationId = 54
                        },
                        new
                        {
                            KineticsCellularFabricId = 3,
                            Code = "014",
                            Colour = "Water Green",
                            Multiplier = 1.0m,
                            Opacity = "Translucent",
                            ProductOptionVariationId = 55
                        },
                        new
                        {
                            KineticsCellularFabricId = 4,
                            Code = "019",
                            Colour = "Agate Red",
                            Multiplier = 1.0m,
                            Opacity = "Translucent",
                            ProductOptionVariationId = 56
                        },
                        new
                        {
                            KineticsCellularFabricId = 5,
                            Code = "021",
                            Colour = "Gray Sheen",
                            Multiplier = 1.0m,
                            Opacity = "Translucent",
                            ProductOptionVariationId = 57
                        },
                        new
                        {
                            KineticsCellularFabricId = 6,
                            Code = "023",
                            Colour = "Royal Gray",
                            Multiplier = 1.0m,
                            Opacity = "Translucent",
                            ProductOptionVariationId = 58
                        },
                        new
                        {
                            KineticsCellularFabricId = 7,
                            Code = "024",
                            Colour = "Jean Blue",
                            Multiplier = 1.0m,
                            Opacity = "Translucent",
                            ProductOptionVariationId = 59
                        },
                        new
                        {
                            KineticsCellularFabricId = 8,
                            Code = "025",
                            Colour = "Black",
                            Multiplier = 1.0m,
                            Opacity = "Translucent",
                            ProductOptionVariationId = 60
                        },
                        new
                        {
                            KineticsCellularFabricId = 9,
                            Code = "026",
                            Colour = "Federal Blue",
                            Multiplier = 1.0m,
                            Opacity = "Translucent",
                            ProductOptionVariationId = 61
                        },
                        new
                        {
                            KineticsCellularFabricId = 10,
                            Code = "030",
                            Colour = "Steel Grey",
                            Multiplier = 1.0m,
                            Opacity = "Translucent",
                            ProductOptionVariationId = 62
                        },
                        new
                        {
                            KineticsCellularFabricId = 11,
                            Code = "070",
                            Colour = "Winter White",
                            Multiplier = 1.0m,
                            Opacity = "Translucent",
                            ProductOptionVariationId = 63
                        },
                        new
                        {
                            KineticsCellularFabricId = 12,
                            Code = "102",
                            Colour = "Aqua Glass",
                            Multiplier = 1.0m,
                            Opacity = "Translucent",
                            ProductOptionVariationId = 64
                        },
                        new
                        {
                            KineticsCellularFabricId = 13,
                            Code = "333",
                            Colour = "Warm Chocolate",
                            Multiplier = 1.0m,
                            Opacity = "Translucent",
                            ProductOptionVariationId = 65
                        },
                        new
                        {
                            KineticsCellularFabricId = 14,
                            Code = "416",
                            Colour = "Taupe A",
                            Multiplier = 1.0m,
                            Opacity = "Translucent",
                            ProductOptionVariationId = 66
                        },
                        new
                        {
                            KineticsCellularFabricId = 15,
                            Code = "512",
                            Colour = "Flax Green",
                            Multiplier = 1.0m,
                            Opacity = "Translucent",
                            ProductOptionVariationId = 67
                        });
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.Fabric.Type.KineticsRollerFabric", b =>
                {
                    b.Property<int>("KineticsRollerFabricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KineticsRollerFabricId"));

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Fabric")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaxHeight")
                        .HasColumnType("int");

                    b.Property<int>("MaxWidth")
                        .HasColumnType("int");

                    b.Property<decimal>("Multiplier")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Opacity")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProductOptionVariationId")
                        .HasColumnType("int");

                    b.HasKey("KineticsRollerFabricId");

                    b.HasAlternateKey("Colour", "Fabric", "Opacity");

                    b.HasIndex("ProductOptionVariationId")
                        .IsUnique();

                    b.ToTable("KineticsRollerFabric");

                    b.HasData(
                        new
                        {
                            KineticsRollerFabricId = 1,
                            Colour = "Black",
                            Fabric = "Adagio",
                            MaxHeight = 2010,
                            MaxWidth = 3100,
                            Multiplier = 1.25m,
                            Opacity = "LF",
                            ProductOptionVariationId = 44
                        },
                        new
                        {
                            KineticsRollerFabricId = 2,
                            Colour = "Chilli",
                            Fabric = "Adagio",
                            MaxHeight = 2010,
                            MaxWidth = 3100,
                            Multiplier = 1.25m,
                            Opacity = "LF",
                            ProductOptionVariationId = 45
                        },
                        new
                        {
                            KineticsRollerFabricId = 3,
                            Colour = "Taupe",
                            Fabric = "Adagio",
                            MaxHeight = 2010,
                            MaxWidth = 3100,
                            Multiplier = 1.25m,
                            Opacity = "LF",
                            ProductOptionVariationId = 46
                        },
                        new
                        {
                            KineticsRollerFabricId = 4,
                            Colour = "Amaze",
                            Fabric = "Austro",
                            MaxHeight = 3000,
                            MaxWidth = 3000,
                            Multiplier = 0.8m,
                            Opacity = "BO",
                            ProductOptionVariationId = 47
                        },
                        new
                        {
                            KineticsRollerFabricId = 5,
                            Colour = "Anchor",
                            Fabric = "Austro",
                            MaxHeight = 3000,
                            MaxWidth = 3000,
                            Multiplier = 0.8m,
                            Opacity = "BO",
                            ProductOptionVariationId = 48
                        },
                        new
                        {
                            KineticsRollerFabricId = 6,
                            Colour = "Apple",
                            Fabric = "Austro",
                            MaxHeight = 3000,
                            MaxWidth = 3000,
                            Multiplier = 0.8m,
                            Opacity = "BO",
                            ProductOptionVariationId = 49
                        },
                        new
                        {
                            KineticsRollerFabricId = 7,
                            Colour = "Charcoal",
                            Fabric = "Fenescreen 10%",
                            MaxHeight = 2200,
                            MaxWidth = 3000,
                            Multiplier = 0.9m,
                            Opacity = "SS",
                            ProductOptionVariationId = 50
                        },
                        new
                        {
                            KineticsRollerFabricId = 8,
                            Colour = "Coyote",
                            Fabric = "Fenescreen 10%",
                            MaxHeight = 2200,
                            MaxWidth = 3000,
                            Multiplier = 0.9m,
                            Opacity = "SS",
                            ProductOptionVariationId = 51
                        },
                        new
                        {
                            KineticsRollerFabricId = 9,
                            Colour = "Glacier White",
                            Fabric = "Fenescreen 10%",
                            MaxHeight = 2200,
                            MaxWidth = 3000,
                            Multiplier = 0.9m,
                            Opacity = "SS",
                            ProductOptionVariationId = 52
                        });
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<Guid>("ExternalMapping")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("InstallHeight")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RemoteChannel")
                        .HasColumnType("int");

                    b.Property<int>("RemoteNumber")
                        .HasColumnType("int");

                    b.Property<int>("Reveal")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.Property<int>("WorksheetId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("WorksheetId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.ProductOption", b =>
                {
                    b.Property<int>("ProductOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductOptionId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductOptionId");

                    b.ToTable("ProductOption");

                    b.HasData(
                        new
                        {
                            ProductOptionId = 1,
                            Name = "FitType"
                        },
                        new
                        {
                            ProductOptionId = 2,
                            Name = "FixingTo"
                        },
                        new
                        {
                            ProductOptionId = 3,
                            Name = "ProductType"
                        },
                        new
                        {
                            ProductOptionId = 4,
                            Name = "Fabric"
                        },
                        new
                        {
                            ProductOptionId = 5,
                            Name = "OperationType"
                        },
                        new
                        {
                            ProductOptionId = 6,
                            Name = "OperationSide"
                        },
                        new
                        {
                            ProductOptionId = 7,
                            Name = "HeadrailColour"
                        },
                        new
                        {
                            ProductOptionId = 8,
                            Name = "SideChannelColour"
                        },
                        new
                        {
                            ProductOptionId = 9,
                            Name = "RollType"
                        },
                        new
                        {
                            ProductOptionId = 10,
                            Name = "ChainColour"
                        },
                        new
                        {
                            ProductOptionId = 11,
                            Name = "ChainLength"
                        },
                        new
                        {
                            ProductOptionId = 12,
                            Name = "BracketType"
                        },
                        new
                        {
                            ProductOptionId = 13,
                            Name = "BracketColour"
                        },
                        new
                        {
                            ProductOptionId = 14,
                            Name = "BottomRailType"
                        },
                        new
                        {
                            ProductOptionId = 15,
                            Name = "BottomRailColour"
                        },
                        new
                        {
                            ProductOptionId = 16,
                            Name = "PelmetType"
                        },
                        new
                        {
                            ProductOptionId = 17,
                            Name = "PelmetColour"
                        });
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.ProductOptionVariation", b =>
                {
                    b.Property<int>("ProductOptionVariationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductOptionVariationId"));

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductOptionId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductOptionVariationId");

                    b.HasIndex("ProductOptionId");

                    b.ToTable("ProductOptionVariation");

                    b.HasData(
                        new
                        {
                            ProductOptionVariationId = 1,
                            Price = 0.0m,
                            ProductOptionId = 1,
                            Value = "Inside"
                        },
                        new
                        {
                            ProductOptionVariationId = 2,
                            Price = 0.0m,
                            ProductOptionId = 1,
                            Value = "Outside"
                        },
                        new
                        {
                            ProductOptionVariationId = 3,
                            Price = 0.0m,
                            ProductOptionId = 2,
                            Value = "Wood"
                        },
                        new
                        {
                            ProductOptionVariationId = 4,
                            Price = 0.0m,
                            ProductOptionId = 3,
                            Value = "Kinetics Cellular"
                        },
                        new
                        {
                            ProductOptionVariationId = 5,
                            Price = 0.0m,
                            ProductOptionId = 3,
                            Value = "Kinetics Roller"
                        },
                        new
                        {
                            ProductOptionVariationId = 6,
                            Price = 250.0m,
                            ProductOptionId = 5,
                            Value = "Lithium-ion"
                        },
                        new
                        {
                            ProductOptionVariationId = 7,
                            Price = 0.0m,
                            ProductOptionId = 5,
                            Value = "Cord"
                        },
                        new
                        {
                            ProductOptionVariationId = 8,
                            Price = 0.0m,
                            ProductOptionId = 5,
                            Value = "Chain"
                        },
                        new
                        {
                            ProductOptionVariationId = 9,
                            Price = 0.00m,
                            ProductOptionId = 6,
                            Value = "Left"
                        },
                        new
                        {
                            ProductOptionVariationId = 10,
                            Price = 0.00m,
                            ProductOptionId = 6,
                            Value = "Right"
                        },
                        new
                        {
                            ProductOptionVariationId = 11,
                            Price = 0.00m,
                            ProductOptionId = 7,
                            Value = "White"
                        },
                        new
                        {
                            ProductOptionVariationId = 12,
                            Price = 0.00m,
                            ProductOptionId = 7,
                            Value = "Black"
                        },
                        new
                        {
                            ProductOptionVariationId = 13,
                            Price = 0.00m,
                            ProductOptionId = 8,
                            Value = "White"
                        },
                        new
                        {
                            ProductOptionVariationId = 14,
                            Price = 0.00m,
                            ProductOptionId = 8,
                            Value = "Black"
                        },
                        new
                        {
                            ProductOptionVariationId = 15,
                            Price = 0.00m,
                            ProductOptionId = 9,
                            Value = "Front"
                        },
                        new
                        {
                            ProductOptionVariationId = 16,
                            Price = 0.00m,
                            ProductOptionId = 9,
                            Value = "Back"
                        },
                        new
                        {
                            ProductOptionVariationId = 17,
                            Price = 0.00m,
                            ProductOptionId = 10,
                            Value = "White"
                        },
                        new
                        {
                            ProductOptionVariationId = 18,
                            Price = 0.00m,
                            ProductOptionId = 10,
                            Value = "Black"
                        },
                        new
                        {
                            ProductOptionVariationId = 19,
                            Price = 0.00m,
                            ProductOptionId = 10,
                            Value = "Grey"
                        },
                        new
                        {
                            ProductOptionVariationId = 20,
                            Price = 32.00m,
                            ProductOptionId = 10,
                            Value = "Stainless"
                        },
                        new
                        {
                            ProductOptionVariationId = 21,
                            Price = 0.00m,
                            ProductOptionId = 11,
                            Value = "750"
                        },
                        new
                        {
                            ProductOptionVariationId = 22,
                            Price = 0.00m,
                            ProductOptionId = 11,
                            Value = "1000"
                        },
                        new
                        {
                            ProductOptionVariationId = 23,
                            Price = 0.00m,
                            ProductOptionId = 11,
                            Value = "1250"
                        },
                        new
                        {
                            ProductOptionVariationId = 24,
                            Price = 0.00m,
                            ProductOptionId = 11,
                            Value = "1500"
                        },
                        new
                        {
                            ProductOptionVariationId = 25,
                            Price = 0.00m,
                            ProductOptionId = 11,
                            Value = "1750"
                        },
                        new
                        {
                            ProductOptionVariationId = 26,
                            Price = 0.00m,
                            ProductOptionId = 11,
                            Value = "2000"
                        },
                        new
                        {
                            ProductOptionVariationId = 27,
                            Price = 0.00m,
                            ProductOptionId = 11,
                            Value = "2250"
                        },
                        new
                        {
                            ProductOptionVariationId = 28,
                            Price = 0.00m,
                            ProductOptionId = 11,
                            Value = "2500"
                        },
                        new
                        {
                            ProductOptionVariationId = 29,
                            Price = 0.00m,
                            ProductOptionId = 11,
                            Value = "2750"
                        },
                        new
                        {
                            ProductOptionVariationId = 30,
                            Price = 0.00m,
                            ProductOptionId = 11,
                            Value = "3000"
                        },
                        new
                        {
                            ProductOptionVariationId = 31,
                            Price = 0.00m,
                            ProductOptionId = 12,
                            Value = "Standard"
                        },
                        new
                        {
                            ProductOptionVariationId = 32,
                            Price = 0.00m,
                            ProductOptionId = 12,
                            Value = "Extra Large"
                        },
                        new
                        {
                            ProductOptionVariationId = 33,
                            Price = 0.00m,
                            ProductOptionId = 13,
                            Value = "White"
                        },
                        new
                        {
                            ProductOptionVariationId = 34,
                            Price = 0.00m,
                            ProductOptionId = 13,
                            Value = "Black"
                        },
                        new
                        {
                            ProductOptionVariationId = 35,
                            Price = 0.00m,
                            ProductOptionId = 14,
                            Value = "Flat"
                        },
                        new
                        {
                            ProductOptionVariationId = 36,
                            Price = 25.00m,
                            ProductOptionId = 14,
                            Value = "Deluxe"
                        },
                        new
                        {
                            ProductOptionVariationId = 37,
                            Price = 0.00m,
                            ProductOptionId = 15,
                            Value = "White"
                        },
                        new
                        {
                            ProductOptionVariationId = 38,
                            Price = 0.00m,
                            ProductOptionId = 15,
                            Value = "Black"
                        },
                        new
                        {
                            ProductOptionVariationId = 39,
                            Price = 0.00m,
                            ProductOptionId = 15,
                            Value = "Silver"
                        },
                        new
                        {
                            ProductOptionVariationId = 40,
                            Price = 0.00m,
                            ProductOptionId = 15,
                            Value = "Off White"
                        },
                        new
                        {
                            ProductOptionVariationId = 41,
                            Price = 0.00m,
                            ProductOptionId = 16,
                            Value = "None"
                        },
                        new
                        {
                            ProductOptionVariationId = 42,
                            Price = 0.00m,
                            ProductOptionId = 17,
                            Value = "White"
                        },
                        new
                        {
                            ProductOptionVariationId = 43,
                            Price = 0.00m,
                            ProductOptionId = 17,
                            Value = "Black"
                        },
                        new
                        {
                            ProductOptionVariationId = 44,
                            Price = 0.00m,
                            ProductOptionId = 4,
                            Value = "Adagio Black LF"
                        },
                        new
                        {
                            ProductOptionVariationId = 45,
                            Price = 0.00m,
                            ProductOptionId = 4,
                            Value = "Adagio Chilli LF"
                        },
                        new
                        {
                            ProductOptionVariationId = 46,
                            Price = 0.00m,
                            ProductOptionId = 4,
                            Value = "Adagio Taupe LF"
                        },
                        new
                        {
                            ProductOptionVariationId = 47,
                            Price = 0.00m,
                            ProductOptionId = 4,
                            Value = "Austro Amaze BO"
                        },
                        new
                        {
                            ProductOptionVariationId = 48,
                            Price = 0.00m,
                            ProductOptionId = 4,
                            Value = "Austro Anchor BO"
                        },
                        new
                        {
                            ProductOptionVariationId = 49,
                            Price = 0.00m,
                            ProductOptionId = 4,
                            Value = "Austro Apple BO"
                        },
                        new
                        {
                            ProductOptionVariationId = 50,
                            Price = 0.00m,
                            ProductOptionId = 4,
                            Value = "Fenescreen 10% Charcoal SS"
                        },
                        new
                        {
                            ProductOptionVariationId = 51,
                            Price = 0.00m,
                            ProductOptionId = 4,
                            Value = "Fenescreen 10% Coyote SS"
                        },
                        new
                        {
                            ProductOptionVariationId = 52,
                            Price = 0.00m,
                            ProductOptionId = 4,
                            Value = "Fenescreen 10% Glacier White SS"
                        },
                        new
                        {
                            ProductOptionVariationId = 53,
                            Price = 0.00m,
                            ProductOptionId = 4,
                            Value = "001 Translucent Cotton"
                        },
                        new
                        {
                            ProductOptionVariationId = 54,
                            Price = 0.00m,
                            ProductOptionId = 4,
                            Value = "005 Translucent Cream"
                        },
                        new
                        {
                            ProductOptionVariationId = 55,
                            Price = 0.00m,
                            ProductOptionId = 4,
                            Value = "014 Translucent Water Green"
                        },
                        new
                        {
                            ProductOptionVariationId = 56,
                            Price = 0.00m,
                            ProductOptionId = 4,
                            Value = "019 Translucent Agate Red"
                        },
                        new
                        {
                            ProductOptionVariationId = 57,
                            Price = 0.00m,
                            ProductOptionId = 4,
                            Value = "021 Translucent Gray Sheen"
                        },
                        new
                        {
                            ProductOptionVariationId = 58,
                            Price = 0.00m,
                            ProductOptionId = 4,
                            Value = "023 Translucent Royal Gray"
                        },
                        new
                        {
                            ProductOptionVariationId = 59,
                            Price = 0.00m,
                            ProductOptionId = 4,
                            Value = "024 Translucent Jean Blue"
                        },
                        new
                        {
                            ProductOptionVariationId = 60,
                            Price = 0.00m,
                            ProductOptionId = 4,
                            Value = "025 Translucent Black"
                        },
                        new
                        {
                            ProductOptionVariationId = 61,
                            Price = 0.00m,
                            ProductOptionId = 4,
                            Value = "026 Translucent Federal Blue"
                        },
                        new
                        {
                            ProductOptionVariationId = 62,
                            Price = 0.00m,
                            ProductOptionId = 4,
                            Value = "030 Translucent Steel Grey"
                        },
                        new
                        {
                            ProductOptionVariationId = 63,
                            Price = 0.00m,
                            ProductOptionId = 4,
                            Value = "070 Translucent Winter White"
                        },
                        new
                        {
                            ProductOptionVariationId = 64,
                            Price = 0.00m,
                            ProductOptionId = 4,
                            Value = "102 Translucent Aqua Glass"
                        },
                        new
                        {
                            ProductOptionVariationId = 65,
                            Price = 0.00m,
                            ProductOptionId = 4,
                            Value = "333 Translucent Warm Chocolate"
                        },
                        new
                        {
                            ProductOptionVariationId = 66,
                            Price = 0.00m,
                            ProductOptionId = 4,
                            Value = "416 Translucent Taupe A"
                        },
                        new
                        {
                            ProductOptionVariationId = 67,
                            Price = 0.00m,
                            ProductOptionId = 4,
                            Value = "512 Translucent Flax Green"
                        });
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.Worksheet", b =>
                {
                    b.Property<int>("WorksheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorksheetId"));

                    b.Property<decimal>("CallOutFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ExternalMapping")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("NewBuild")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("WorksheetId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Worksheet");
                });

            modelBuilder.Entity("ProductProductOptionVariation", b =>
                {
                    b.Property<int>("OptionVariationsProductOptionVariationId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsProductId")
                        .HasColumnType("int");

                    b.HasKey("OptionVariationsProductOptionVariationId", "ProductsProductId");

                    b.HasIndex("ProductsProductId");

                    b.ToTable("ProductProductOptionVariation");
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.Fabric.Type.KineticsCellularFabric", b =>
                {
                    b.HasOne("Lewiss.Pricing.Data.Model.ProductOptionVariation", "ProductOptionVariation")
                        .WithOne()
                        .HasForeignKey("Lewiss.Pricing.Data.Model.Fabric.Type.KineticsCellularFabric", "ProductOptionVariationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductOptionVariation");
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.Fabric.Type.KineticsRollerFabric", b =>
                {
                    b.HasOne("Lewiss.Pricing.Data.Model.ProductOptionVariation", "ProductOptionVariation")
                        .WithOne()
                        .HasForeignKey("Lewiss.Pricing.Data.Model.Fabric.Type.KineticsRollerFabric", "ProductOptionVariationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductOptionVariation");
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.Product", b =>
                {
                    b.HasOne("Lewiss.Pricing.Data.Model.Worksheet", "Worksheet")
                        .WithMany()
                        .HasForeignKey("WorksheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worksheet");
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.ProductOptionVariation", b =>
                {
                    b.HasOne("Lewiss.Pricing.Data.Model.ProductOption", "ProductOption")
                        .WithMany("ProductOptionVariation")
                        .HasForeignKey("ProductOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductOption");
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.Worksheet", b =>
                {
                    b.HasOne("Lewiss.Pricing.Data.Model.Customer", "Customer")
                        .WithMany("CurrentWorksheets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ProductProductOptionVariation", b =>
                {
                    b.HasOne("Lewiss.Pricing.Data.Model.ProductOptionVariation", null)
                        .WithMany()
                        .HasForeignKey("OptionVariationsProductOptionVariationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lewiss.Pricing.Data.Model.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.Customer", b =>
                {
                    b.Navigation("CurrentWorksheets");
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.ProductOption", b =>
                {
                    b.Navigation("ProductOptionVariation");
                });
#pragma warning restore 612, 618
        }
    }
}
