// <auto-generated />
using System;
using Lewiss.Pricing.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lewiss.Pricing.Data.Migrations
{
    [DbContext(typeof(PricingDbContext))]
    partial class PricingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("ExternalMapping")
                        .HasColumnType("char(36)");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Mobile")
                        .IsUnique();

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<bool>("AboveHeightConstraint")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ExternalMapping")
                        .HasColumnType("char(36)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("RemoteChannel")
                        .HasColumnType("int");

                    b.Property<int>("RemoteNumber")
                        .HasColumnType("int");

                    b.Property<int>("Reveal")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.Property<int>("WorksheetId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("WorksheetId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.ProductOption", b =>
                {
                    b.Property<int>("ProductOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductOptionId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProductOptionId");

                    b.ToTable("ProductOption");

                    b.HasData(
                        new
                        {
                            ProductOptionId = 1,
                            Name = "FitType"
                        },
                        new
                        {
                            ProductOptionId = 2,
                            Name = "FixingTo"
                        },
                        new
                        {
                            ProductOptionId = 3,
                            Name = "ProductType"
                        },
                        new
                        {
                            ProductOptionId = 4,
                            Name = "Fabric"
                        });
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.ProductOptionVariation", b =>
                {
                    b.Property<int>("ProductOptionVariationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductOptionVariationId"));

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProductOptionId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProductOptionVariationId");

                    b.HasIndex("ProductOptionId");

                    b.ToTable("ProductOptionVariation");

                    b.HasData(
                        new
                        {
                            ProductOptionVariationId = 1,
                            Price = 0.0m,
                            ProductOptionId = 1,
                            Value = "Inside"
                        },
                        new
                        {
                            ProductOptionVariationId = 2,
                            Price = 0.0m,
                            ProductOptionId = 1,
                            Value = "Outside"
                        },
                        new
                        {
                            ProductOptionVariationId = 3,
                            Price = 0.0m,
                            ProductOptionId = 2,
                            Value = "Wood"
                        },
                        new
                        {
                            ProductOptionVariationId = 4,
                            Price = 0.0m,
                            ProductOptionId = 3,
                            Value = "Kinetics Cellular"
                        },
                        new
                        {
                            ProductOptionVariationId = 5,
                            Price = 0.0m,
                            ProductOptionId = 3,
                            Value = "Kinetics Roller"
                        },
                        new
                        {
                            ProductOptionVariationId = 6,
                            Price = 0.0m,
                            ProductOptionId = 4,
                            Value = "Translucent White"
                        },
                        new
                        {
                            ProductOptionVariationId = 7,
                            Price = 0.0m,
                            ProductOptionId = 4,
                            Value = "Everyday Vinyl Collection - Polar"
                        });
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.Worksheet", b =>
                {
                    b.Property<int>("WorksheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WorksheetId"));

                    b.Property<decimal>("CallOutFee")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("ExternalMapping")
                        .HasColumnType("char(36)");

                    b.Property<bool>("NewBuild")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("WorksheetId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Worksheet");
                });

            modelBuilder.Entity("ProductProductOptionVariation", b =>
                {
                    b.Property<int>("OptionVariationsProductOptionVariationId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsProductId")
                        .HasColumnType("int");

                    b.HasKey("OptionVariationsProductOptionVariationId", "ProductsProductId");

                    b.HasIndex("ProductsProductId");

                    b.ToTable("ProductProductOptionVariation");
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.Product", b =>
                {
                    b.HasOne("Lewiss.Pricing.Data.Model.Worksheet", "Worksheet")
                        .WithMany()
                        .HasForeignKey("WorksheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worksheet");
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.ProductOptionVariation", b =>
                {
                    b.HasOne("Lewiss.Pricing.Data.Model.ProductOption", "ProductOption")
                        .WithMany("ProductOptionVariation")
                        .HasForeignKey("ProductOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductOption");
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.Worksheet", b =>
                {
                    b.HasOne("Lewiss.Pricing.Data.Model.Customer", "Customer")
                        .WithMany("CurrentWorksheets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ProductProductOptionVariation", b =>
                {
                    b.HasOne("Lewiss.Pricing.Data.Model.ProductOptionVariation", null)
                        .WithMany()
                        .HasForeignKey("OptionVariationsProductOptionVariationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lewiss.Pricing.Data.Model.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.Customer", b =>
                {
                    b.Navigation("CurrentWorksheets");
                });

            modelBuilder.Entity("Lewiss.Pricing.Data.Model.ProductOption", b =>
                {
                    b.Navigation("ProductOptionVariation");
                });
#pragma warning restore 612, 618
        }
    }
}
